"""Qualification Artifact Envelope v1 canonicalization and validation.

This file is the canonical source. Consumer Skills import generated byte-for-byte
copies so their installed packages remain independently executable.
"""

import copy
import datetime as _datetime
import hashlib
import json
import re
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple


ENVELOPE_VERSION = "qualification-artifact-envelope/v1"
PRODUCER_POLICY_VERSION = "qualification-artifact-producer-policy/v1"
EVIDENCE_CLASSES = (
    "static_snapshot",
    "fixture",
    "diagnostic",
    "operational_only",
    "qualification",
    "formal_acceptance",
)
AUTHORITATIVENESS = ("non_authoritative", "operational", "authoritative")
STATUSES = ("passed", "failed", "blocked", "not_applicable", "not_verified")
IDENTITY_FIELDS = (
    "source",
    "installed_package",
    "native_binary",
    "image",
    "runtime",
    "driver",
    "toolchain",
    "model",
    "tokenizer",
    "processor",
    "workload",
    "hardware",
    "capability_policy",
)

_DIGEST = re.compile(r"^sha256:[0-9a-f]{64}$")
_GIT_SHA = re.compile(r"^[0-9a-f]{40}$")
_VERSION = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
_SCHEMA_VERSION = re.compile(r"^[a-z0-9][a-z0-9-]*/v([1-9][0-9]*)$")
_POLICY_VERSION = re.compile(r"^v[1-9][0-9]*$")
_TIMESTAMP = re.compile(
    r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:\.[0-9]+)?Z$"
)

_TOP_LEVEL_FIELDS = (
    "schema_version",
    "artifact_id",
    "producer",
    "producer_version",
    "created_at",
    "subject_identity",
    "input_artifact_digests",
    "evidence_class",
    "authoritativeness",
    "acceptance_eligible",
    "status",
    "blockers",
    "primary_blocker",
    "resume_point",
    "claim_boundary",
    "unverified_scope",
    "digest",
)

# Policy is code-owned, versioned, and closed-world. Exclusions override the
# general schema allowlist and prevent accidental ownership expansion.
PRODUCER_POLICY = {
    "version": PRODUCER_POLICY_VERSION,
    "producers": {
        "diagnosing-bugs/qualification-artifact-validator": {
            "schemas": (
                ENVELOPE_VERSION,
                "dlc-profile-evidence-manifest/v1",
                "dlc-profile-validation-result/v1",
                "dlc-perf-breakdown/v1",
            ),
            "excluded_schemas": (),
            "max_evidence_class": "diagnostic",
            "max_authoritativeness": "non_authoritative",
            "acceptance_eligible": False,
        },
        "diagnosing-bugs/profile-artifact-validator": {
            "schemas": (
                "dlc-profile-evidence-manifest/v1",
                "dlc-profile-validation-result/v1",
            ),
            "excluded_schemas": (),
            "max_evidence_class": "diagnostic",
            "max_authoritativeness": "non_authoritative",
            "acceptance_eligible": False,
        },
        "diagnosing-bugs/perf-breakdown-analyzer": {
            "schemas": ("dlc-perf-breakdown/v1",),
            "excluded_schemas": (),
            "max_evidence_class": "diagnostic",
            "max_authoritativeness": "non_authoritative",
            "acceptance_eligible": False,
        },
        "diagnosing-bugs/profile-semantic-producer": {
            "schemas": ("dlc-profile-semantic-artifact/v1",),
            "excluded_schemas": (),
            "max_evidence_class": "diagnostic",
            "max_authoritativeness": "non_authoritative",
            "acceptance_eligible": False,
        },
        "model-adaptation/distributed-collective-fixture": {
            "schemas": (
                "vllm-cl-distributed-collective-qualification/v1",
                "vllm-cl-distributed-collective-qualification/v2",
            ),
            "excluded_schemas": (),
            "max_evidence_class": "fixture",
            "max_authoritativeness": "non_authoritative",
            "acceptance_eligible": False,
        },
        "model-adaptation/live-identity-collector": {
            "schemas": ("vllm-cl-live-identity/v1",),
            "excluded_schemas": (),
            "max_evidence_class": "operational_only",
            "max_authoritativeness": "non_authoritative",
            "acceptance_eligible": False,
        },
        "model-adaptation/dlccl-qualification-runner": {
            "schemas": (
                "vllm-cl-distributed-collective-qualification/v1",
                "vllm-cl-distributed-collective-qualification/v2",
            ),
            "excluded_schemas": (),
            "max_evidence_class": "qualification",
            "max_authoritativeness": "operational",
            "acceptance_eligible": False,
        },
        "model-adaptation/qualification-runner": {
            "schemas": (
                ENVELOPE_VERSION,
                "vllm-cl-local-kv-qualification/v1",
                "vllm-cl-distributed-collective-qualification/v1",
                "vllm-cl-distributed-collective-qualification/v2",
                "vllm-cl-graph-qualification/v1",
                "vllm-cl-model-precision-qualification/v1",
                "vllm-cl-quantization-qualification/v1",
                "vllm-cl-performance-experiment-record/v1",
            ),
            "excluded_schemas": (
                "vllm-cl-model-precision-qualification/v1",
                "vllm-cl-quantization-qualification/v1",
            ),
            "max_evidence_class": "qualification",
            "max_authoritativeness": "operational",
            "acceptance_eligible": False,
        },
        "modelzoo-image-validation/formal-qualification-runner": {
            "schemas": (
                "vllm-cl-model-precision-qualification/v1",
                "vllm-cl-quantization-qualification/v1",
                "vllm-cl-performance-experiment-record/v1",
            ),
            "excluded_schemas": (),
            "max_evidence_class": "formal_acceptance",
            "max_authoritativeness": "authoritative",
            "acceptance_eligible": True,
        },
    },
}

_IDENTITY_SHAPES = {
    "source": ("kind", "repository", "revision", "dirty", "snapshot_digest"),
    "installed_package": ("name", "version", "path", "digest"),
    "native_binary": ("digest",),
    "image": ("image_id", "digest"),
    "runtime": ("name", "version", "digest"),
    "driver": ("name", "version", "digest"),
    "toolchain": ("name", "version", "digest"),
    "model": ("model_id", "revision", "digest"),
    "tokenizer": ("revision", "digest"),
    "processor": ("revision", "digest"),
    "workload": ("digest",),
    "hardware": ("generation", "topology_digest"),
    "capability_policy": ("policy_id", "version", "digest"),
}


def canonical_json(document: Mapping[str, Any]) -> bytes:
    """Return canonical UTF-8 JSON bytes, omitting only top-level digest."""
    if not isinstance(document, Mapping):
        raise TypeError("document must be a mapping")
    payload = dict(document)
    payload.pop("digest", None)
    _reject_floats(payload, "$")
    return json.dumps(
        payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")


def canonical_digest(document: Mapping[str, Any]) -> str:
    return "sha256:" + hashlib.sha256(canonical_json(document)).hexdigest()


def seal_envelope(document: Mapping[str, Any]) -> Dict[str, Any]:
    sealed = copy.deepcopy(dict(document))
    sealed["digest"] = canonical_digest(sealed)
    return sealed


def identity_blockers(identity: Any) -> List[Dict[str, str]]:
    """Return missing full-identity blockers in contract field order."""
    if not isinstance(identity, Mapping):
        return [{"status": "blocked", "code": "missing_identity", "path": "$.subject_identity"}]
    return [
        {"status": "blocked", "code": "missing_identity", "path": f"$.subject_identity.{field}"}
        for field in IDENTITY_FIELDS
        if field not in identity or (identity[field] is None and field != "processor")
    ]


def stale_identity_blockers(
    sealed_identity: Mapping[str, Any], current_identity: Mapping[str, Any]
) -> List[Dict[str, str]]:
    """Invalidate evidence when any identity class changes or disappears."""
    blockers = []
    for field in IDENTITY_FIELDS:
        if (
            field not in sealed_identity
            or field not in current_identity
            or sealed_identity[field] != current_identity[field]
        ):
            blockers.append(
                {"status": "not_verified", "code": "stale_identity", "path": f"$.subject_identity.{field}"}
            )
    return blockers


def aggregate_blockers(
    blockers: Sequence[Mapping[str, str]],
) -> Tuple[str, Optional[Dict[str, str]]]:
    """Aggregate status and select one primary blocker independent of input order."""
    if not blockers:
        return "passed", None

    status_rank = {"failed": 0, "blocked": 1, "not_verified": 2}
    normalized = [dict(blocker) for blocker in blockers]
    primary = min(
        normalized,
        key=lambda blocker: (
            status_rank[blocker["status"]],
            blocker.get("code", ""),
            blocker.get("path", ""),
        ),
    )
    return primary["status"], primary


def validate_envelope(
    document: Any,
    extension_fields: Sequence[str] = (),
    accepted_schema_versions: Sequence[str] = (),
) -> List[Dict[str, str]]:
    """Validate Envelope v1 and producer policy, returning deterministic errors."""
    if not isinstance(document, Mapping):
        return [_error("invalid_type", "$")]
    errors: List[Dict[str, str]] = []
    allowed_fields = set(_TOP_LEVEL_FIELDS) | set(extension_fields)
    fields = set(document)
    for field in sorted(fields - allowed_fields):
        errors.append(_error("unknown_field", f"$.{field}"))
    for field in _TOP_LEVEL_FIELDS:
        if field not in document:
            errors.append(_error("missing_required_field", f"$.{field}"))
    for field in extension_fields:
        if field not in document:
            errors.append(_error("missing_required_field", f"$.{field}"))

    schema_version = document.get("schema_version")
    match = _SCHEMA_VERSION.fullmatch(schema_version) if isinstance(schema_version, str) else None
    if (
        match is None
        or (
            match.group(1) != "1"
            and schema_version not in set(accepted_schema_versions)
        )
    ):
        errors.append(_error("unsupported_schema_version", "$.schema_version"))

    errors.extend(_validate_producer_policy(document))
    missing_identity = identity_blockers(document.get("subject_identity"))
    declared_blockers = document.get("blockers")
    covered_missing = {
        (item.get("code"), item.get("path"))
        for item in declared_blockers
        if isinstance(item, Mapping) and item.get("status") == "blocked"
    } if isinstance(declared_blockers, list) else set()
    errors.extend(
        blocker for blocker in missing_identity
        if (blocker["code"], blocker["path"]) not in covered_missing
    )
    if isinstance(document.get("subject_identity"), Mapping):
        errors.extend(_validate_identity(document["subject_identity"]))
    errors.extend(_validate_scalars(document))
    errors.extend(_validate_collections(document))

    if "digest" in document:
        try:
            expected_digest = canonical_digest(document)
        except (TypeError, ValueError):
            errors.append(_error("invalid_canonical_value", "$"))
        else:
            if (
                not isinstance(document["digest"], str)
                or not _DIGEST.fullmatch(document["digest"])
                or document["digest"] != expected_digest
            ):
                errors.append(_error("digest_mismatch", "$.digest"))

    source = document.get("subject_identity", {}).get("source") if isinstance(document.get("subject_identity"), Mapping) else None
    if isinstance(source, Mapping) and source.get("kind") == "static_snapshot":
        if document.get("evidence_class") != "static_snapshot":
            errors.append(_error("static_snapshot_boundary", "$.evidence_class"))
        if document.get("acceptance_eligible") is True:
            errors.append(_error("static_snapshot_boundary", "$.acceptance_eligible"))
        if document.get("authoritativeness") != "non_authoritative":
            errors.append(_error("static_snapshot_boundary", "$.authoritativeness"))

    blockers = document.get("blockers")
    if isinstance(blockers, list) and all(_is_blocker(item) for item in blockers):
        expected_status, expected_primary = aggregate_blockers(blockers)
        if blockers and document.get("status") != expected_status:
            errors.append(_error("inconsistent_status", "$.status"))
        if document.get("primary_blocker") != expected_primary:
            errors.append(_error("inconsistent_primary_blocker", "$.primary_blocker"))
        if not blockers and document.get("status") not in ("passed", "not_applicable"):
            errors.append(_error("inconsistent_status", "$.status"))

    return _deduplicate(errors)


def _validate_producer_policy(document: Mapping[str, Any]) -> List[Dict[str, str]]:
    producer = document.get("producer")
    rule = PRODUCER_POLICY["producers"].get(producer)
    if rule is None:
        return [_error("unknown_producer", "$.producer")]
    schema = document.get("schema_version")
    if schema in rule["excluded_schemas"]:
        return [_error("producer_schema_excluded", "$.schema_version")]
    if schema not in rule["schemas"]:
        return [_error("producer_schema_forbidden", "$.schema_version")]
    evidence = document.get("evidence_class")
    if evidence in EVIDENCE_CLASSES and EVIDENCE_CLASSES.index(evidence) > EVIDENCE_CLASSES.index(rule["max_evidence_class"]):
        return [_error("producer_evidence_exceeded", "$.evidence_class")]
    authority = document.get("authoritativeness")
    if authority in AUTHORITATIVENESS and AUTHORITATIVENESS.index(authority) > AUTHORITATIVENESS.index(rule["max_authoritativeness"]):
        return [_error("producer_authority_exceeded", "$.authoritativeness")]
    if document.get("acceptance_eligible") is True and not rule["acceptance_eligible"]:
        return [_error("producer_acceptance_forbidden", "$.acceptance_eligible")]
    if document.get("acceptance_eligible") is True and evidence != "formal_acceptance":
        return [_error("acceptance_requires_formal_evidence", "$.evidence_class")]
    return []


def _validate_identity(identity: Mapping[str, Any]) -> List[Dict[str, str]]:
    errors: List[Dict[str, str]] = []
    for field in sorted(set(identity) - set(IDENTITY_FIELDS)):
        errors.append(_error("unknown_field", f"$.subject_identity.{field}"))
    for field in IDENTITY_FIELDS:
        value = identity.get(field)
        if field == "processor" and value is None:
            continue
        if field not in identity or value is None:
            continue
        path = f"$.subject_identity.{field}"
        if not isinstance(value, Mapping):
            errors.append(_error("invalid_type", path))
            continue
        allowed = _IDENTITY_SHAPES[field]
        for nested in sorted(set(value) - set(allowed)):
            errors.append(_error("unknown_field", f"{path}.{nested}"))
        for nested in allowed:
            if nested not in value:
                errors.append(_error("missing_identity", f"{path}.{nested}"))

    source = identity.get("source")
    if isinstance(source, Mapping):
        kind = source.get("kind")
        if kind == "git":
            if not _nonempty(source.get("repository")):
                errors.append(_error("missing_identity", "$.subject_identity.source.repository"))
            if not isinstance(source.get("revision"), str) or not _GIT_SHA.fullmatch(source["revision"]):
                errors.append(_error("missing_identity", "$.subject_identity.source.revision"))
            if not isinstance(source.get("dirty"), bool):
                errors.append(_error("missing_identity", "$.subject_identity.source.dirty"))
            if source.get("snapshot_digest") is not None:
                errors.append(_error("invalid_identity", "$.subject_identity.source.snapshot_digest"))
        elif kind == "static_snapshot":
            if source.get("repository") is not None or source.get("revision") is not None or source.get("dirty") is not None:
                errors.append(_error("static_snapshot_boundary", "$.subject_identity.source"))
            if not _valid_digest(source.get("snapshot_digest")):
                errors.append(_error("missing_identity", "$.subject_identity.source.snapshot_digest"))
        else:
            errors.append(_error("invalid_identity", "$.subject_identity.source.kind"))

    for field in ("native_binary", "image", "runtime", "driver", "toolchain", "workload", "capability_policy"):
        value = identity.get(field)
        if isinstance(value, Mapping) and not _valid_digest(value.get("digest")):
            errors.append(_error("missing_identity", f"$.subject_identity.{field}.digest"))
    for field in ("model", "tokenizer", "processor"):
        value = identity.get(field)
        if not isinstance(value, Mapping):
            continue
        if not _nonempty(value.get("revision")) and not _valid_digest(value.get("digest")):
            errors.append(_error("missing_identity", f"$.subject_identity.{field}.revision_or_digest"))
        if value.get("digest") is not None and not _valid_digest(value.get("digest")):
            errors.append(_error("invalid_identity", f"$.subject_identity.{field}.digest"))
    hardware = identity.get("hardware")
    if isinstance(hardware, Mapping) and not _valid_digest(hardware.get("topology_digest")):
        errors.append(_error("missing_identity", "$.subject_identity.hardware.topology_digest"))
    policy = identity.get("capability_policy")
    if isinstance(policy, Mapping) and (not isinstance(policy.get("version"), str) or not _POLICY_VERSION.fullmatch(policy["version"])):
        errors.append(_error("invalid_identity", "$.subject_identity.capability_policy.version"))
    package = identity.get("installed_package")
    if isinstance(package, Mapping):
        if not _valid_digest(package.get("digest")):
            errors.append(_error("missing_identity", "$.subject_identity.installed_package.digest"))
        if not isinstance(package.get("path"), str) or not package["path"].startswith("/"):
            errors.append(_error("invalid_identity", "$.subject_identity.installed_package.path"))
    nonempty_fields = {
        "installed_package": ("name", "version", "path"),
        "image": ("image_id",),
        "runtime": ("name", "version"),
        "driver": ("name", "version"),
        "toolchain": ("name", "version"),
        "model": ("model_id",),
        "hardware": ("generation",),
        "capability_policy": ("policy_id",),
    }
    for field, nested_fields in nonempty_fields.items():
        value = identity.get(field)
        if not isinstance(value, Mapping):
            continue
        for nested in nested_fields:
            if nested in value and not _nonempty(value[nested]):
                errors.append(
                    _error("invalid_identity", f"$.subject_identity.{field}.{nested}")
                )
    for field in ("model", "tokenizer", "processor"):
        value = identity.get(field)
        if isinstance(value, Mapping):
            revision = value.get("revision")
            if revision is not None and not _nonempty(revision):
                errors.append(
                    _error("invalid_identity", f"$.subject_identity.{field}.revision")
                )
    return errors


def _validate_scalars(document: Mapping[str, Any]) -> List[Dict[str, str]]:
    errors = []
    for field in ("artifact_id", "producer", "claim_boundary"):
        if field in document and not _nonempty(document[field]):
            errors.append(_error("invalid_value", f"$.{field}"))
    if "producer_version" in document and (not isinstance(document["producer_version"], str) or not _VERSION.fullmatch(document["producer_version"])):
        errors.append(_error("invalid_value", "$.producer_version"))
    created_at = document.get("created_at")
    if created_at is not None and not _valid_timestamp(created_at):
        errors.append(_error("invalid_value", "$.created_at"))
    if document.get("evidence_class") not in EVIDENCE_CLASSES:
        errors.append(_error("invalid_value", "$.evidence_class"))
    if document.get("authoritativeness") not in AUTHORITATIVENESS:
        errors.append(_error("invalid_value", "$.authoritativeness"))
    if not isinstance(document.get("acceptance_eligible"), bool):
        errors.append(_error("invalid_type", "$.acceptance_eligible"))
    if document.get("status") not in STATUSES:
        errors.append(_error("invalid_value", "$.status"))
    resume = document.get("resume_point")
    if resume is not None and not _nonempty(resume):
        errors.append(_error("invalid_value", "$.resume_point"))
    return errors


def _validate_collections(document: Mapping[str, Any]) -> List[Dict[str, str]]:
    errors = []
    digests = document.get("input_artifact_digests")
    if not isinstance(digests, list):
        errors.append(_error("invalid_type", "$.input_artifact_digests"))
    elif len(digests) != len(set(item for item in digests if isinstance(item, str))) or not all(_valid_digest(item) for item in digests):
        errors.append(_error("invalid_value", "$.input_artifact_digests"))
    blockers = document.get("blockers")
    if not isinstance(blockers, list):
        errors.append(_error("invalid_type", "$.blockers"))
    else:
        serialized = []
        for index, blocker in enumerate(blockers):
            path = f"$.blockers[{index}]"
            if not isinstance(blocker, Mapping):
                errors.append(_error("invalid_type", path))
            elif not _is_blocker(blocker):
                errors.append(_error("invalid_blocker", path))
            else:
                serialized.append(
                    json.dumps(blocker, sort_keys=True, separators=(",", ":"))
                )
        if len(serialized) != len(set(serialized)):
            errors.append(_error("duplicate_blocker", "$.blockers"))
    primary = document.get("primary_blocker")
    if primary is not None and not _is_blocker(primary):
        errors.append(_error("invalid_blocker", "$.primary_blocker"))
    scope = document.get("unverified_scope")
    if not isinstance(scope, list) or not all(_nonempty(item) for item in scope) or len(scope or []) != len(set(scope or [])):
        errors.append(_error("invalid_value", "$.unverified_scope"))
    return errors


def _reject_floats(value: Any, path: str) -> None:
    if isinstance(value, float):
        raise ValueError(f"floating-point value is not canonical at {path}")
    if isinstance(value, Mapping):
        for key, nested in value.items():
            _reject_floats(nested, f"{path}.{key}")
    elif isinstance(value, list):
        for index, nested in enumerate(value):
            _reject_floats(nested, f"{path}[{index}]")


def _valid_timestamp(value: Any) -> bool:
    if not isinstance(value, str) or not _TIMESTAMP.fullmatch(value):
        return False
    try:
        parsed = _datetime.datetime.fromisoformat(value[:-1] + "+00:00")
    except ValueError:
        return False
    return parsed.tzinfo is not None


def _valid_digest(value: Any) -> bool:
    return isinstance(value, str) and _DIGEST.fullmatch(value) is not None


def _nonempty(value: Any) -> bool:
    return isinstance(value, str) and bool(value)


def _is_blocker(value: Any) -> bool:
    return (
        isinstance(value, Mapping)
        and set(value) == {"status", "code", "path"}
        and value["status"] in ("failed", "blocked", "not_verified")
        and _nonempty(value["code"])
        and isinstance(value["path"], str)
        and value["path"].startswith("$")
    )


def _error(code: str, path: str) -> Dict[str, str]:
    return {"code": code, "path": path}


def _deduplicate(errors: Sequence[Dict[str, str]]) -> List[Dict[str, str]]:
    seen = set()
    result = []
    for error in errors:
        identity = (error["code"], error["path"])
        if identity not in seen:
            seen.add(identity)
            result.append(error)
    return result
